Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -31,4 +31,12 @@ jobs:
           GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
         run: |
           pulumi up
+
+      - name: show job status
+        if: always()
+        run: echo $status
+        env:
+          status: ${{job.status}}
+
+      # if: ${{ success() || failure() }}
         
